Added GET /api/articles/:articleId endpoint
wakenado/be-news-api pull request #5
Opened 2022-02-17 09:38 UTC by wakenado

2022-02-17 10:47 UTC, Angaca commented on controllers/app.controllers.js
> +      res.status(404).send({ message: "404 - Not Found" });
You should promise reject here and write a custom error handling function to catch this custom error

2022-02-17 10:48 UTC, Angaca commented on controllers/app.controllers.js
> +      res.status(200).send({ message: response });
needds to change accordingly

2022-02-17 10:49 UTC, Angaca commented on __tests__/app.test.js
> +      expect(response.body.message[0]).toEqual({
it shouldn't be in a key of message and when we send a single element it shouldn't be in an array

2022-02-17 10:49 UTC, Angaca requested changes
You need to amend few details in your code, please see my comments

2022-02-17 13:11 UTC, wakenado commented on controllers/app.controllers.js
> +      res.status(404).send({ message: "404 - Not Found" });
Done

2022-02-17 13:17 UTC, wakenado commented on __tests__/app.test.js
> +      expect(response.body.message[0]).toEqual({
Done

2022-02-17 15:14 UTC, Angaca requested changes
Almost there, we should't attach any status to our normal responses. Any status assertion in the test should go down request(app).expect(200) (or any other status code you expect). Moreover anything you send should be in a relevant key. Article should be in a key of article and not being free in the body

2022-02-18 12:01 UTC, Angaca commented on controllers/app.controllers.js
> +  res.status(200).send({ topics: newsTopics });
can rename newTopics to topics so you can only send {topics}

2022-02-18 12:12 UTC, merged

2022-02-18 12:13 UTC, wakenado commented on controllers/app.controllers.js
> +  res.status(200).send({ topics: newsTopics });
Done